version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
      BUILD_CONFIG: Release
jobs:
  build-test:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet tool install -g dotnet-reportgenerator-globaltool
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover < /dev/null
      - run: curl -s https://codecov.io/bash > codecov
      - run: chmod +x codecov
      - run: ./codecov -f ./src/MySQLQueryDivider.Tests/coverage.opencover.xml
  build-push:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build -c Release -p:Version=${CIRCLE_TAG}
      - run: dotnet test -c Release --no-build -p:Version=${CIRCLE_TAG}
      - run: dotnet pack ./src/MySQLQueryDivider/MySQLQueryDivider.csproj -c Release -p:Version=${CIRCLE_TAG}
      - run: dotnet nuget push ./src/MySQLQueryDivider/bin/Release/MySQLQueryDivider.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package --skip-duplicate -k ${NUGET_KEY}
      - store_artifacts:
          path: ./src/MySQLQueryDivider/bin/Release
          destination: ./MySQLQueryDivider/
workflows:
  build-and-push:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - build-push:
          filters:
            tags:
              only: /^[0-9](\.[0-9]){2}$/
            branches:
              ignore: /.*/
